language: java
sudo: false

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  - pip install --user codecov

script:
  - ./gradlew --info check jacocoTestReport

after_success:
  - ./gradlew jacocoTestReport
  - codecov