language: java
sudo: false

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  - pip install --user codecov
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in .travis/secring.gpg.enc -out vertx-guice/local.secring.gpg -d

script:
  - ./gradlew --info check jacocoTestReport

after_success:
  - ./gradlew jacocoTestReport
  - codecov

deploy:
  -
    provider: script
    script: .travis/deploy.sh
    on:
      repo: intappx/vertx-guice
      branch: master
  -
    provider: script
    script: .travis/deploy.sh
    on:
      repo: intappx/vertx-guice
      tags: true